spring:
  profiles:
    active:
    include: secret
  output:
    ansi:
      enabled: always

  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/sbb__dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password:

  security:
      oauth2:
        client:
          registration:
            kakao:
              scope:
              client-name: Kakao
              authorization-grant-type: authorization_code
              redirect-uri: '${custom.site.baseUrl}/{action}/oauth2/code/{registrationId}'
              client-authentication-method: POST
          provider:
            kakao:
              authorization-uri: https://kauth.kakao.com/oauth/authorize
              token-uri: https://kauth.kakao.com/oauth/token
              user-info-uri: https://kapi.kakao.com/v2/user/me
              user-name-attribute: id

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 1000

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
custom:
  site:
    baseUrl: http://localhost